Client created
Traceback (most recent call last):
  File "d:\OneDrive - LTTS\Desktop\waste\main.py", line 20, in <module>
    client.set_attribute(node_id, ua.AttributeIds.Value, value)
AttributeError: 'Client' object has no attribute 'set_attribute'
