Session created
Client disconnected
Traceback (most recent call last):
  File "d:\OneDrive - LTTS\Desktop\Shavali\main.py", line 72, in <module>
    main()
  File "d:\OneDrive - LTTS\Desktop\Shavali\main.py", line 62, in main
    subscribe_to_values(session)
  File "d:\OneDrive - LTTS\Desktop\Shavali\main.py", line 18, in subscribe_to_values
    subscription_id = session.create_subscription(2000, ua.SubscriptionDiagnosticsDataType())
AttributeError: 'CreateSessionResult' object has no attribute 'create_subscription'
